server:
  port: 8002

spring:
  application:
    name: donation-camp-service
    
  datasource:
    url: jdbc:oracle:thin:@//localhost:1521/XEPDB1
    username: hr
    password: hr
  jpa:
    show-sql: true
    
    hibernate:
      ddl-auto: update
      
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8000/eureka